version: '3'
services:
  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
  webserver:
    image: puckel/docker-airflow:latest
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./warehouse/source:/usr/local/airflow/warehouse/source
      - ./warehouse/raw:/usr/local/airflow/warehouse/raw
      - ./warehouse/final:/usr/local/airflow/warehouse/final
      - ./warehouse/reports:/usr/local/airflow/warehouse/reports
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3